source_stream_name = "credit_profile_events"
output_stream_name = "credit_profile_predictions"
model_bucket = "jai-mlops-data"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stream_profile_predictions"
lambda_function_name = "profile_predictions_lambda"