[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "Trailing whitespace",
    "line-too-long",
    "trailing-whitespace"
    "unused-import",
    "unused-variable",
    "too-many-instance-attributes",
    "too-many-arguments"


]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
