channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=22.1.2
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - dataclasses==0.6
  - psutil==5.9.1
  - scikit-learn==1.1.2
  - typing-extensions==4.3.0
name: mlflow-env
